"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.streets_service_api import StreetsServiceApi  # noqa: E501


class TestStreetsServiceApi(unittest.TestCase):
    """StreetsServiceApi unit test stubs"""

    def setUp(self):
        self.api = StreetsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_intersection_by_address(self):
        """Test case for get_intersection_by_address

        Nearest Intesection By Address.  # noqa: E501
        """
        pass

    def test_get_intersection_by_location(self):
        """Test case for get_intersection_by_location

        Nearest Intesection By Location.  # noqa: E501
        """
        pass

    def test_get_nearest_speed_limit(self):
        """Test case for get_nearest_speed_limit

        Nearest Speedlimit.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
