"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.email_verification_service_api import EmailVerificationServiceApi  # noqa: E501


class TestEmailVerificationServiceApi(unittest.TestCase):
    """EmailVerificationServiceApi unit test stubs"""

    def setUp(self):
        self.api = EmailVerificationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_validate_email_address(self):
        """Test case for validate_email_address

        ValidateEmailAddress  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
