"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.geolocation_service_api import GeolocationServiceApi  # noqa: E501


class TestGeolocationServiceApi(unittest.TestCase):
    """GeolocationServiceApi unit test stubs"""

    def setUp(self):
        self.api = GeolocationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_location_by_ip_address(self):
        """Test case for get_location_by_ip_address

        Location By IP Address.  # noqa: E501
        """
        pass

    def test_get_location_by_wi_fi_access_point(self):
        """Test case for get_location_by_wi_fi_access_point

        Location by WiFi Access Point.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
