"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.risks_service_api import RisksServiceApi  # noqa: E501


class TestRisksServiceApi(unittest.TestCase):
    """RisksServiceApi unit test stubs"""

    def setUp(self):
        self.api = RisksServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_crime_risk_by_address(self):
        """Test case for get_crime_risk_by_address

        Get Crime Risk By Address  # noqa: E501
        """
        pass

    def test_get_crime_risk_by_address_batch(self):
        """Test case for get_crime_risk_by_address_batch

        Post Crime Risk By Address  # noqa: E501
        """
        pass

    def test_get_crime_risk_by_location(self):
        """Test case for get_crime_risk_by_location

        Get Crime Risk By  Location  # noqa: E501
        """
        pass

    def test_get_crime_risk_by_location_batch(self):
        """Test case for get_crime_risk_by_location_batch

        Post Crime Risk By Location  # noqa: E501
        """
        pass

    def test_get_distance_to_coast_by_address(self):
        """Test case for get_distance_to_coast_by_address

        Get Distance To Flood Hazard By Address  # noqa: E501
        """
        pass

    def test_get_distance_to_coast_by_address_batch(self):
        """Test case for get_distance_to_coast_by_address_batch

        Post Distance To Flood Hazard By Address  # noqa: E501
        """
        pass

    def test_get_distance_to_coast_by_location(self):
        """Test case for get_distance_to_coast_by_location

        Get Distance To Flood Hazard By Location  # noqa: E501
        """
        pass

    def test_get_distance_to_coast_by_location_batch(self):
        """Test case for get_distance_to_coast_by_location_batch

        Post Distance To Flood Hazard By Location  # noqa: E501
        """
        pass

    def test_get_earthquake_history(self):
        """Test case for get_earthquake_history

        Earthquake History  # noqa: E501
        """
        pass

    def test_get_earthquake_risk_by_address(self):
        """Test case for get_earthquake_risk_by_address

        Get Earthquake Risk By Address  # noqa: E501
        """
        pass

    def test_get_earthquake_risk_by_address_batch(self):
        """Test case for get_earthquake_risk_by_address_batch

        Post Earthquake Risk By Address  # noqa: E501
        """
        pass

    def test_get_earthquake_risk_by_location(self):
        """Test case for get_earthquake_risk_by_location

        Get Earthquake Risk By Location  # noqa: E501
        """
        pass

    def test_get_earthquake_risk_by_location_batch(self):
        """Test case for get_earthquake_risk_by_location_batch

        Post Earthquake Risk By Location  # noqa: E501
        """
        pass

    def test_get_fire_history(self):
        """Test case for get_fire_history

        Get Fire History  # noqa: E501
        """
        pass

    def test_get_fire_risk_by_address(self):
        """Test case for get_fire_risk_by_address

        Get Fire Risk By Address  # noqa: E501
        """
        pass

    def test_get_fire_risk_by_address_batch(self):
        """Test case for get_fire_risk_by_address_batch

        Post Fire Risk By Address  # noqa: E501
        """
        pass

    def test_get_fire_risk_by_location(self):
        """Test case for get_fire_risk_by_location

        Get Fire Risk By Location  # noqa: E501
        """
        pass

    def test_get_fire_risk_by_location_batch(self):
        """Test case for get_fire_risk_by_location_batch

        Post Fire Risk By Location  # noqa: E501
        """
        pass

    def test_get_fire_station_by_address(self):
        """Test case for get_fire_station_by_address

        Get Fire Station By Address  # noqa: E501
        """
        pass

    def test_get_fire_station_by_location(self):
        """Test case for get_fire_station_by_location

        Get Fire Station By Location  # noqa: E501
        """
        pass

    def test_get_flood_risk_by_address(self):
        """Test case for get_flood_risk_by_address

        Get Flood Risk By Address  # noqa: E501
        """
        pass

    def test_get_flood_risk_by_address_batch(self):
        """Test case for get_flood_risk_by_address_batch

        Post Flood Risk By Address  # noqa: E501
        """
        pass

    def test_get_flood_risk_by_location(self):
        """Test case for get_flood_risk_by_location

        Get Flood Risk By Location  # noqa: E501
        """
        pass

    def test_get_flood_risk_by_location_batch(self):
        """Test case for get_flood_risk_by_location_batch

        Post Flood Risk By Location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
