"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.schools_service_api import SchoolsServiceApi  # noqa: E501


class TestSchoolsServiceApi(unittest.TestCase):
    """SchoolsServiceApi unit test stubs"""

    def setUp(self):
        self.api = SchoolsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_schools_by_address(self):
        """Test case for get_schools_by_address

        Search Nearby Schools by Address  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
