"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.address_verification_service_api import AddressVerificationServiceApi  # noqa: E501


class TestAddressVerificationServiceApi(unittest.TestCase):
    """AddressVerificationServiceApi unit test stubs"""

    def setUp(self):
        self.api = AddressVerificationServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_city_state_province(self):
        """Test case for get_city_state_province

        GetCityStateProvince  # noqa: E501
        """
        pass

    def test_get_postal_codes(self):
        """Test case for get_postal_codes

        GetPostalCodes  # noqa: E501
        """
        pass

    def test_validate_mailing_address(self):
        """Test case for validate_mailing_address

        ValidateMailingAddress  # noqa: E501
        """
        pass

    def test_validate_mailing_address_premium(self):
        """Test case for validate_mailing_address_premium

        ValidateMailingAddressPremium  # noqa: E501
        """
        pass

    def test_validate_mailing_address_pro(self):
        """Test case for validate_mailing_address_pro

        ValidateMailingAddressPro  # noqa: E501
        """
        pass

    def test_validate_mailing_address_uscan(self):
        """Test case for validate_mailing_address_uscan

        ValidateMailingAddressUSCAN  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
