"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.addresses_service__api import AddressesServiceApi  # noqa: E501


class TestAddressesServiceApi(unittest.TestCase):
    """AddressesServiceApi unit test stubs"""

    def setUp(self):
        self.api = AddressesServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_addresses_count_by_boundary_name(self):
        """Test case for get_addresses_count_by_boundary_name

        Addresses Count by Boundary Name.  # noqa: E501
        """
        pass

    def test_get_addresses_countby_boundary(self):
        """Test case for get_addresses_countby_boundary

        Addresses count by Boundary.  # noqa: E501
        """
        pass

    def test_get_addressesby_boundary(self):
        """Test case for get_addressesby_boundary

        Addresses by Boundary.  # noqa: E501
        """
        pass

    def test_get_addressesby_boundary_name(self):
        """Test case for get_addressesby_boundary_name

        Addresses by Boundary Name.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
