"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import unittest

import com.precisely.apis
from com.precisely.apis.api.neighborhoods_service__api import NeighborhoodsServiceApi  # noqa: E501


class TestNeighborhoodsServiceApi(unittest.TestCase):
    """NeighborhoodsServiceApi unit test stubs"""

    def setUp(self):
        self.api = NeighborhoodsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_place_by_location(self):
        """Test case for get_place_by_location

        Place By Location.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
