"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 11.9.2
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from com.precisely.apis.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from com.precisely.apis.exceptions import ApiAttributeError


def lazy_import():
    from com.precisely.apis.model.business_id import BusinessId
    from com.precisely.apis.model.contact_details import ContactDetails
    from com.precisely.apis.model.distance import Distance
    from com.precisely.apis.model.domestic_ultimate_business import DomesticUltimateBusiness
    from com.precisely.apis.model.employee_count import EmployeeCount
    from com.precisely.apis.model.geometry import Geometry
    from com.precisely.apis.model.global_ultimate_business import GlobalUltimateBusiness
    from com.precisely.apis.model.parent_business import ParentBusiness
    from com.precisely.apis.model.poi_classification import PoiClassification
    from com.precisely.apis.model.sales_volume import SalesVolume
    globals()['BusinessId'] = BusinessId
    globals()['ContactDetails'] = ContactDetails
    globals()['Distance'] = Distance
    globals()['DomesticUltimateBusiness'] = DomesticUltimateBusiness
    globals()['EmployeeCount'] = EmployeeCount
    globals()['Geometry'] = Geometry
    globals()['GlobalUltimateBusiness'] = GlobalUltimateBusiness
    globals()['ParentBusiness'] = ParentBusiness
    globals()['PoiClassification'] = PoiClassification
    globals()['SalesVolume'] = SalesVolume


class Poi(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (str,),  # noqa: E501
            'poi_id': (str,),  # noqa: E501
            'name': (str,),  # noqa: E501
            'pbkey': (str,),  # noqa: E501
            'parent_pbkey': (str,),  # noqa: E501
            'geocode_confidence': (str,),  # noqa: E501
            'brand_name': (str,),  # noqa: E501
            'trade_name': (str,),  # noqa: E501
            'franchise_name': (str,),  # noqa: E501
            'open24_hours': (str,),  # noqa: E501
            'distance': (Distance,),  # noqa: E501
            'business_id': (BusinessId,),  # noqa: E501
            'relevance_score': (str,),  # noqa: E501
            'contact_details': (ContactDetails,),  # noqa: E501
            'poi_classification': (PoiClassification,),  # noqa: E501
            'sales_volume': ([SalesVolume],),  # noqa: E501
            'employee_count': (EmployeeCount,),  # noqa: E501
            'year_start': (str,),  # noqa: E501
            'goods_agent_code': (str,),  # noqa: E501
            'goods_agent_code_description': (str,),  # noqa: E501
            'legal_status_code': (str,),  # noqa: E501
            'organization_status_code': (str,),  # noqa: E501
            'organization_status_code_description': (str,),  # noqa: E501
            'subsidary_indicator': (str,),  # noqa: E501
            'subsidary_indicator_description': (str,),  # noqa: E501
            'parent_business': (ParentBusiness,),  # noqa: E501
            'domestic_ultimate_business': (DomesticUltimateBusiness,),  # noqa: E501
            'global_ultimate_indicator': (str,),  # noqa: E501
            'global_ultimate_business': (GlobalUltimateBusiness,),  # noqa: E501
            'family_members': (str,),  # noqa: E501
            'hierarchy_code': (str,),  # noqa: E501
            'ticker_symbol': (str,),  # noqa: E501
            'exchange_name': (str,),  # noqa: E501
            'ceo_name': (str,),  # noqa: E501
            'ceo_title': (str,),  # noqa: E501
            'geometry': (Geometry,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'poi_id': 'poiId',  # noqa: E501
        'name': 'name',  # noqa: E501
        'pbkey': 'pbkey',  # noqa: E501
        'parent_pbkey': 'parentPbkey',  # noqa: E501
        'geocode_confidence': 'geocodeConfidence',  # noqa: E501
        'brand_name': 'brandName',  # noqa: E501
        'trade_name': 'tradeName',  # noqa: E501
        'franchise_name': 'franchiseName',  # noqa: E501
        'open24_hours': 'open24Hours',  # noqa: E501
        'distance': 'distance',  # noqa: E501
        'business_id': 'businessId',  # noqa: E501
        'relevance_score': 'relevanceScore',  # noqa: E501
        'contact_details': 'contactDetails',  # noqa: E501
        'poi_classification': 'poiClassification',  # noqa: E501
        'sales_volume': 'salesVolume',  # noqa: E501
        'employee_count': 'employeeCount',  # noqa: E501
        'year_start': 'yearStart',  # noqa: E501
        'goods_agent_code': 'goodsAgentCode',  # noqa: E501
        'goods_agent_code_description': 'goodsAgentCodeDescription',  # noqa: E501
        'legal_status_code': 'legalStatusCode',  # noqa: E501
        'organization_status_code': 'organizationStatusCode',  # noqa: E501
        'organization_status_code_description': 'organizationStatusCodeDescription',  # noqa: E501
        'subsidary_indicator': 'subsidaryIndicator',  # noqa: E501
        'subsidary_indicator_description': 'subsidaryIndicatorDescription',  # noqa: E501
        'parent_business': 'parentBusiness',  # noqa: E501
        'domestic_ultimate_business': 'domesticUltimateBusiness',  # noqa: E501
        'global_ultimate_indicator': 'globalUltimateIndicator',  # noqa: E501
        'global_ultimate_business': 'globalUltimateBusiness',  # noqa: E501
        'family_members': 'familyMembers',  # noqa: E501
        'hierarchy_code': 'hierarchyCode',  # noqa: E501
        'ticker_symbol': 'tickerSymbol',  # noqa: E501
        'exchange_name': 'exchangeName',  # noqa: E501
        'ceo_name': 'ceoName',  # noqa: E501
        'ceo_title': 'ceoTitle',  # noqa: E501
        'geometry': 'geometry',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """Poi - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            poi_id (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            pbkey (str): [optional]  # noqa: E501
            parent_pbkey (str): [optional]  # noqa: E501
            geocode_confidence (str): [optional]  # noqa: E501
            brand_name (str): [optional]  # noqa: E501
            trade_name (str): [optional]  # noqa: E501
            franchise_name (str): [optional]  # noqa: E501
            open24_hours (str): [optional]  # noqa: E501
            distance (Distance): [optional]  # noqa: E501
            business_id (BusinessId): [optional]  # noqa: E501
            relevance_score (str): [optional]  # noqa: E501
            contact_details (ContactDetails): [optional]  # noqa: E501
            poi_classification (PoiClassification): [optional]  # noqa: E501
            sales_volume ([SalesVolume]): [optional]  # noqa: E501
            employee_count (EmployeeCount): [optional]  # noqa: E501
            year_start (str): [optional]  # noqa: E501
            goods_agent_code (str): [optional]  # noqa: E501
            goods_agent_code_description (str): [optional]  # noqa: E501
            legal_status_code (str): [optional]  # noqa: E501
            organization_status_code (str): [optional]  # noqa: E501
            organization_status_code_description (str): [optional]  # noqa: E501
            subsidary_indicator (str): [optional]  # noqa: E501
            subsidary_indicator_description (str): [optional]  # noqa: E501
            parent_business (ParentBusiness): [optional]  # noqa: E501
            domestic_ultimate_business (DomesticUltimateBusiness): [optional]  # noqa: E501
            global_ultimate_indicator (str): [optional]  # noqa: E501
            global_ultimate_business (GlobalUltimateBusiness): [optional]  # noqa: E501
            family_members (str): [optional]  # noqa: E501
            hierarchy_code (str): [optional]  # noqa: E501
            ticker_symbol (str): [optional]  # noqa: E501
            exchange_name (str): [optional]  # noqa: E501
            ceo_name (str): [optional]  # noqa: E501
            ceo_title (str): [optional]  # noqa: E501
            geometry (Geometry): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """Poi - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (str): [optional]  # noqa: E501
            poi_id (str): [optional]  # noqa: E501
            name (str): [optional]  # noqa: E501
            pbkey (str): [optional]  # noqa: E501
            parent_pbkey (str): [optional]  # noqa: E501
            geocode_confidence (str): [optional]  # noqa: E501
            brand_name (str): [optional]  # noqa: E501
            trade_name (str): [optional]  # noqa: E501
            franchise_name (str): [optional]  # noqa: E501
            open24_hours (str): [optional]  # noqa: E501
            distance (Distance): [optional]  # noqa: E501
            business_id (BusinessId): [optional]  # noqa: E501
            relevance_score (str): [optional]  # noqa: E501
            contact_details (ContactDetails): [optional]  # noqa: E501
            poi_classification (PoiClassification): [optional]  # noqa: E501
            sales_volume ([SalesVolume]): [optional]  # noqa: E501
            employee_count (EmployeeCount): [optional]  # noqa: E501
            year_start (str): [optional]  # noqa: E501
            goods_agent_code (str): [optional]  # noqa: E501
            goods_agent_code_description (str): [optional]  # noqa: E501
            legal_status_code (str): [optional]  # noqa: E501
            organization_status_code (str): [optional]  # noqa: E501
            organization_status_code_description (str): [optional]  # noqa: E501
            subsidary_indicator (str): [optional]  # noqa: E501
            subsidary_indicator_description (str): [optional]  # noqa: E501
            parent_business (ParentBusiness): [optional]  # noqa: E501
            domestic_ultimate_business (DomesticUltimateBusiness): [optional]  # noqa: E501
            global_ultimate_indicator (str): [optional]  # noqa: E501
            global_ultimate_business (GlobalUltimateBusiness): [optional]  # noqa: E501
            family_members (str): [optional]  # noqa: E501
            hierarchy_code (str): [optional]  # noqa: E501
            ticker_symbol (str): [optional]  # noqa: E501
            exchange_name (str): [optional]  # noqa: E501
            ceo_name (str): [optional]  # noqa: E501
            ceo_title (str): [optional]  # noqa: E501
            geometry (Geometry): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
