# flake8: noqa

"""
    Precisely APIs

    Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.  # noqa: E501

    The version of the OpenAPI document: 12.0.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "12.0.0"

# import ApiClient
from com.precisely.apis.api_client import ApiClient

# import Configuration
from com.precisely.apis.configuration import Configuration

# import exceptions
from com.precisely.apis.exceptions import OpenApiException
from com.precisely.apis.exceptions import ApiAttributeError
from com.precisely.apis.exceptions import ApiTypeError
from com.precisely.apis.exceptions import ApiValueError
from com.precisely.apis.exceptions import ApiKeyError
from com.precisely.apis.exceptions import ApiException
